// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0hfV0sj_jT38YLlAB0WGddtU3VysMhL4',
    appId: '1:868472456107:web:0f37a78f04d638b9c648ee',
    messagingSenderId: '868472456107',
    projectId: 'e-commerece-firebase',
    authDomain: 'e-commerece-firebase.firebaseapp.com',
    storageBucket: 'e-commerece-firebase.appspot.com',
    measurementId: 'G-809YS4Y1Z1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKXVwuZZWXs1p-gg47C2K7uIFEqd2xJ9o',
    appId: '1:868472456107:android:b51bf6fc788fb3dec648ee',
    messagingSenderId: '868472456107',
    projectId: 'e-commerece-firebase',
    storageBucket: 'e-commerece-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-vMxe0tcz1r2ZBl4obXaJfyxyj_6iCCM',
    appId: '1:868472456107:ios:a7854bb2fa4a1bdcc648ee',
    messagingSenderId: '868472456107',
    projectId: 'e-commerece-firebase',
    storageBucket: 'e-commerece-firebase.appspot.com',
    iosBundleId: 'com.surya.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-vMxe0tcz1r2ZBl4obXaJfyxyj_6iCCM',
    appId: '1:868472456107:ios:cf97d541160d0b61c648ee',
    messagingSenderId: '868472456107',
    projectId: 'e-commerece-firebase',
    storageBucket: 'e-commerece-firebase.appspot.com',
    iosBundleId: 'com.surya.ecommerce.RunnerTests',
  );
}
